config/routes.rb
Rails.application.routes.draw do
  get 'products' => 'products#index'
  # get 'products', to: 'products#index'
  
  post 'products', to: 'products#index'

  # get 'carts/show'

  resources :items
  
  devise_for :users
  
  root 'home#index'

  resources :order_items

  resource :carts, only: [:show, :create]
  get 'carts/success'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
    has_many :order_items
end

app/models/order.rb
class Order < ApplicationRecord
    has_many :order_items
    before_save :set_subtotal

    def subtotal
        order_items.collect{ |oi| if oi.valid? then oi.quantity * oi.unit_price else 0 end }.sum
    end

    private

    def set_subtotal
        self.subtotal = subtotal
    end

end

app/models/order_item.rb
class OrderItem < ApplicationRecord
    belongs_to :order
    belongs_to :item

    before_save :set_unit_price
    before_save :set_total

    def unit_price
        # if Record exists
        if persisted?
            self[:unit_price]
        else
            item.price
        end
    end

    def total 
        unit_price * quantity
    end

    private 

        def set_unit_price
            self[:unit_price] = unit_price
        end

        def set_total
            self[:total] = total
        end
        
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    include ApplicationHelper

    protected

    def authenticate_admin!
        authenticate_user!
        flash[:alert] = "You are not authorized to access this page." unless current_user.admin?
        redirect_to '/' unless current_user.admin?
    end

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController

  def success
  end

  def create

    @session = Stripe::Checkout::Session.create({
      payment_method_types: ['card'],
      line_items: [{
        price_data: {
          currency: 'inr',
          product_data: {
            name: 'T-shirt',
          },
          unit_amount: 50000,
        },
        quantity: 1,
      }],
      mode: 'payment',
      discounts: [{
        coupon: '123456'
      }],
      success_url: 'http://localhost:3000/carts/success',
      cancel_url: 'http://localhost:3000/carts',
    })
    respond_to do |format|
      format.js
    end

  end

  def show
    @order_items = current_order.order_items
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: %i[ show edit update destroy ]

  before_action :authenticate_admin!, only: [:new, :create, :edit, :update, :destroy]

  # GET /items or /items.json
  def index
    @items = Item.all
    @order_item = current_order.order_items.new
  end

  # GET /items/1 or /items/1.json
  def show
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items or /items.json
  def create
    @item = Item.new(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: "Item was successfully created." }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1 or /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @item, notice: "Item was successfully updated." }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1 or /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url, notice: "Item was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def item_params
      params.require(:item).permit(:name, :category, :price, :reviews, :colors, :sizes)
    end
end

app/controllers/order_items_controller.rb
class OrderItemsController < ApplicationController

    def create
        @order = current_order
        @order_item = @order.order_items.new(oi_params)
        @order.save
        session[:order_id] = @order.id
    end


    def update
        @order = current_order
        @order_item = @order.order_items.find(params[:id])
        @order_item.update_attributes(oi_params)

        @order_items = @order.order_items       # To reassign value for using AJAX
    end

    
    def destroy
        @order = current_order
        @order_item = @order.order_items.find(params[:id])
        @order_item.destroy

        @order_items = @order.order_items      # To reassign value for using AJAX
    end



    private 

        def oi_params
            params.require(:order_item).permit(:item_id, :quantity)
        end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def index
    @items = Item.all
    @order_item = current_order.order_items.new
    
    if request.post?
      
      # render 'hello'
      # redirect_to '/products/hello'

      keyword="%" + params[:search].to_s + "%"
      keyword = keyword.downcase

      if params[:search].present?
        @items = Item.where("name LIKE ? OR category LIKE ? OR colors LIKE ? OR sizes LIKE ?", keyword, keyword, keyword, keyword)

        # @items = Item.find_by_sql ["Select * from items WHERE name like ?",keyword]

        puts "Item Value ======================= #{@items.inspect}"
        render 'index'

      else
        @items = Item.all
      end

    end

  end

  private 

  def product_params
    params.require(:item).permit(:search)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

    def current_order

        # current_order ||= Order.find_by_id(session[:order_id]).presence || Order.new

        if !session[:order_id].nil?
            Order.find(session[:order_id])
        else
            Order.new
        end
    end
    
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/carts/_cart.html.erb
<%= link_to "#{current_order.order_items.size} items with value: #{current_order.subtotal}$ ", carts_path, class: "btn btn-light" %>

app/views/carts/_cart_item.html.erb
 
<table>
<thead>
  <tr>
    <th>Name</th>
    <th>Category</th>
    <th>Price</th>
    <th>Reviews</th>
    <th>Sizes</th>
    <th>Colors</th>
    <th colspan="3"></th>
  </tr>
</thead>

<tbody>
  <% @order_items.each do |oi| %>
    <tr>
      <td><%= oi.item.name %></td>
      <td><%= oi.item.category %></td>
      <td><%= oi.item.price %></td>
      <td><%= oi.item.reviews %></td>
      <td><%= oi.item.sizes %></td>
      <td><%= oi.item.colors %></td>

      <td>
        <%= form_for oi, remote: true do |f| %>
          <%= f.hidden_field :item_id, value: oi.item.id %>
          <%= f.number_field :quantity, min: 1, max: 10, value: oi.quantity %>
          <%= f.submit 'Update Cart' %>
        <% end %> 
      </td>
      <td> Subtotal: <%= oi.total %> </td>
      
      <td>
      <%= link_to 'Remove', order_item_path(oi), method: :delete, remote: true, data: { confirm: 'Are you sure?' } %>
      </td>

    </tr>
  <% end %>
</tbody>
</table>

<br>

<% if @order_items.present? %>
   <%= button_to "Checkout", carts_path, method: :post, params: {id: @order_items.first.item.id}, remote: true, class: 'btn btn-success' %>
<% end %>



<h2> Total price: <%= current_order.subtotal %> </h2>

app/views/carts/create.js.erb
var stripe = Stripe("<%= ENV['STRIPE_PUBLIC_KEY'] %>");

  stripe.redirectToCheckout({
    sessionId: '<%= @session.id %>'
  }).then(function (result) {
    console.log(result.error.message);
});

app/views/carts/show.html.erb
<p id="notice"><%= notice %></p>

<h1>Cart Items</h1>

<div id="cart_item">
  <%= render 'carts/cart_item' %>
</div>

app/views/carts/success.html.erb
<html>
  <head><title>Thanks for your order!</title></head>
  <body>
    <div class="container mt-5">
        <h1>Thanks for your order!</h1>
        <p class="font-italic">
        We appreciate your business!
        If you have any questions, please email
        <a href="mailto:orders@example.com">orders@example.com</a>.
        </p>
        <%= link_to 'Continue Shopping', '/', class: 'btn btn-primary text-white' %>
    </div>
  </body>
</html>

app/views/home/index.html.erb
<div class="container-fluid">
    <div class="row  position-relative">
        <%= image_tag 'main1.jpg', class: 'img-fluid p-4 opacity-image' %>
        <div class="text-on-image text-white">
            <p class="text2"> Save up to 50% &#8212; use code <strong> BLACKFRIDAY </strong> for an extra 20% off on selective styles. </p>
            <p class="text1 mb-5"> For Everything in your List </p>
            <a class="btn btn-outline-warning btn-lg text-warning mr-3" href="/products"> Shop Now </a>    
            <a class="btn btn-warning btn-lg text-dark" href="/carts"> Check Cart </a>
        </div>
    </div>
</div>

<div class="jumbotron text-center p-2 mt-5">
  <h1 class="display-4 fw-bold"> <b> Providing the Best since 2010 </b> </h1>
</div>

<div class="container-fluid">
  <div class="row">
    <div class="col-6">
    <%= image_tag 'banner1.jpg', class: 'img-fluid p-4' %>
    </div>
    <div class="col-6">
    <%= image_tag 'banner2.jpg', class: 'img-fluid p-4' %>
    </div>
    

  </div>
</div>

<footer class="mt-5">
<nav class="navbar d-block text-white text-center bg-dark">
  <span class="navbar-text">
    Made with ❤ by <a href="https://www.linkedin.com/in/jot-singh-chawla-708846138/" target="_blank" class="text-white">JS</a>
  </span>
</nav>
</footer>

app/views/items/_form.html.erb
<%= form_with(model: item, local: true) do |form| %>
  <% if item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :category %>
    <%= form.text_field :category %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.number_field :price %>
  </div>

  <div class="field">
    <%= form.label :reviews %>
    <%= form.text_field :reviews %>
  </div>

  <div class="field">
    <%= form.label :colors %>
    <%= form.text_field :colors %>
  </div>
  
  <div class="field">
    <%= form.label :sizes %>
    <%= form.text_field :sizes %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/items/edit.html.erb
<h1>Editing Item</h1>

<%= render 'form', item: @item %>

<%= link_to 'Show', @item %> |
<%= link_to 'Back', items_path %>

app/views/items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Items</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Category</th>
      <th>Price</th>
      <th>Reviews</th>
      <th>Sizes</th>
      <th>Colors</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @items.each do |item| %>
      <tr>
        <td><%= item.name %></td>
        <td><%= item.category %></td>
        <td><%= item.price %></td>
        <td><%= item.reviews %></td>
        <td><%= item.sizes %></td>
        <td><%= item.colors %></td>
        <td><%= link_to 'Show', item %></td>
        <td><%= link_to 'Edit', edit_item_path(item) %></td>
        <td><%= link_to 'Destroy', item, method: :delete, data: { confirm: 'Are you sure?' } %></td>

     

      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Item', new_item_path %> <br>

app/views/items/new.html.erb
<h1>New Item</h1>

<%= render 'form', item: @item %>

<%= link_to 'Back', items_path %>

app/views/items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @item.name %>
</p>

<p>
  <strong>Category:</strong>
  <%= @item.category %>
</p>

<p>
  <strong>Price:</strong>
  <%= @item.price %>
</p>

<p>
  <strong>Reviews:</strong>
  <%= @item.reviews %>
</p>

<p>
  <strong>Sizes:</strong>
  <%= @item.sizes %>
</p>

<p>
  <strong>Colors:</strong>
  <%= @item.colors %>
</p>

<%= link_to 'Edit', edit_item_path(@item) %> |
<%= link_to 'Back', items_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Shoelush</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous"/>
    
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

    <script src="https://js.stripe.com/v3/"></script>


  </head>

  <body>

  
  <nav class="navbar fixed-top navbar-expand-lg navbar-light" style="background-color: #eee;">
  <a class="navbar-brand" href="/">
    <%= image_tag 'logo.png', alt: 'Shoelush', width: 60, height: 30, class: "d-inline-block align-top"  %>
    Shoelush
  </a>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/products">Products</a>
        </li>
        <% if user_signed_in? && current_user.admin? %>
          <li class="nav-item">
            <a class="nav-link" href="/items">Change Items</a>
          </li>
        <% end %>
        <li class="nav-item">
          <a class="nav-link" href="/carts">Cart</a>
        </li>
      </ul> 
      <ul class="navbar-nav ml-auto">
          <li class="nav-item">
          <p class="navbar-text m-auto d-flex align-items-center">
          <% if user_signed_in? %>
            <%= image_tag "https://lh3.googleusercontent.com/-7NfTuMgr-UQ/AAAAAAAAAAI/AAAAAAAAAAA/AMZuucknKfQpbLxUPbKotnYffSyZ6_jCbA/photo.jpg?sz=46", class: 'img-fluid rounded-circle mr-1', style: "height: 40px; width: 40px" %>
            
            <span class="mr-2" data-toggle="tooltip" data-placement="bottom" title="<%= current_user.email %>">
              <strong class="pr-2 h4"><%= current_user.email.capitalize %></strong>
            </span>

            <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> &thinsp;|&thinsp;
            <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
          <% else %>
            <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> &thinsp;|&thinsp;     
            <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
          <% end %>
          </p>
        </li>
      
        </ul>
    </div>
  </nav>
  
  <div class="mt-5 pt-3"></div>

    <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
    <% end %>

    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>

    <%= yield %>

  </body>
</html>

app/views/order_items/create.js.erb
$('#cart').html("<%= escape_javascript( render('carts/cart') ) %>");

app/views/order_items/destroy.js.erb
$('#cart_item').html("<%= escape_javascript( render('carts/cart_item') ) %>");

app/views/order_items/update.js.erb
$('#cart_item').html("<%= escape_javascript( render('carts/cart_item') ) %>");

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<div class="jumbotron row text-start pl-5 p-2 mt-4">
  <div class="col-6">
    <h1 class="display-4"> <b> Our range of Products </b> </h1>
  </div>
    
  <div class="col-4 offset-2 d-flex align-self-center justify-content-end  pr-5">
    <%= form_with url: "/products", local: true, method: :post, class: "form-inline" do |form| %>  
      <%= form.text_field :search, placeholder: "Search here", class: "form-control mr-2" %>
      <%= form.submit "Search", class: "btn btn-success" %>
    <% end %>
  </div>
</div>


<% if !@items.empty? %>

  <div class="container-fluid">
    <div class="row">
        <% @items.each_with_index do |item, index| %>
        
        <div class="col-4">
            <div class="position-relative my-4">
              <div class="title-topleft"> <%= item.category %> </div>
              
              
              <% link = ["https://www.linkpicture.com/q/sh.webp", "https://www.linkpicture.com/q/shoes1.webp", "https://www.linkpicture.com/q/abc_3.jpg"] %> 
              <% x=0 %>
              <%= image_tag link[index], style: "width:100%; height: 450px", alt: 'Shoes-image'  %>
              <% x = 1 %>
              </a>
              
              <div class="mt-2 d-flex mb-5 pb-3 bellow_post text-dark"> 
                  <div class="w-100">
                    <span class="h2 my-auto "> <%= item.name %> </span>
                    <span class="h5 mt-0 float-right "> <%= item.reviews %> <i class="fas fa-star"></i> </span>
  
                        <%= form_for @order_item, remote: true, :html => {:class => 'form-inline mt-2' }  do |f| %>
                          <%= f.hidden_field :item_id, value: item.id %>
                          <%= f.number_field :quantity, min: 1, max: 10, value: 1, class: "form-control form-control-sm" %>
                          <%= f.submit 'Add to Cart', class: " ml-2 btn btn-sm btn-success" %>
                          <% end %> 
                  </div>
              </div>
            </div>
        </div>
        <% end %>

    </div>
      
  </div>

<% else %>
    <h1> No items found </h1>
<% end %>

<br>

<div id="cart" class="container-fluid mb-5">
    <%= render 'carts/cart' %>
</div>

app/views/products/show.html.erb
<h1>Products#show</h1>
<p>Find me in app/views/products/show.html.erb</p>